import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./globals.module.css";
import Link from "next/link";
import Header from "./src/components/header/index";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={styles.container}>
        <Header />
        {children}
      </body>
    </html>
  );
}
