import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
/* import "bootstrap/dist/css/bootstrap"; */
import PagesLayout from "./src/components/layouts/PagesLayout";

export const metadata: Metadata = {
  title: "Mikiniki",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <PagesLayout>{children}</PagesLayout>;
}
